ABOUT_SUFFIX = '/about'
CONTACT_SUFFIX = '/contact'
IDEAS_SUFFIX = '/ideas'
PEOPLE_SUFFIX = '/people'
CAREERS_SUFFIX = '/careers'
WORK_SUFFIX = '/work'

ABBVIE_LOGO_ID = '_508'


IDEAS_SUMMARY_ID = '_421'
IDEAS_SUMMARY_LEFT = '_298'
IDEAS_SUMMARY_MID = '_300'
IDEAS_SUMMARY_RIGHT = '_302'
