ABOUT_SUFFIX = '/about'
CONTACT_SUFFIX = '/contact'
IDEAS_SUFFIX = '/ideas'
PEOPLE_SUFFIX = '/people'
CAREERS_SUFFIX = '/careers'
WORK_SUFFIX = '/work'

ABBVIE_ALT_TEXT = 'abbvie-logo-sm.jpg'
AETNA_ALT_TEXT = 'aetna-logo-sm.jpg'
BCBS_ALT_TEXT = 'bcbs-logo.jpg'
FOUNDATION_MED_ALT_TEXT = 'foundation-logo-sm.jpg'
HUMANA_ALT_TEXT = 'humana-logo.jpg'
MEDECISION_ALT_TEXT = 'medc-logo-sm.jpg'
MGH_ALT_TEXT = 'mgh-logo.jpg'
OPTUM_ALT_TEXT = 'optum-logo-sm.jpg'
RED_HEALTH_ALT_TEXT = 'Client_Redbrick.jpg'
TUFTS_ALT_TEXT = 'tuffs-logo.jpg'
VERIZON_ALT_TEXT = 'verizon-logos-sm.jpg'
YOU_ALT_TEXT = 'youplus.jpg'

GET_IN_TOUCH_ALT_TEXT = 'Button_Interested.jpg'

ITEM_SUMMARY_PAGE = ''

IDEAS_SUMMARY_ID = '_421'
IDEAS_SUMMARY_LEFT = '_298'
IDEAS_SUMMARY_MID = '_300'
IDEAS_SUMMARY_RIGHT = '_302'
